services:
  - type: web
    name: telegram-bot
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: BOT_TOKEN
        sync: false
      - key: BOT_USERNAME
        sync: false
      - key: DATABASE_URL
        value: ./data/bot.db
      - key: LOG_LEVEL
        value: info
      - key: ADMIN_USER_IDS
        sync: false
      - key: GOOGLE_SHEETS_ID
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: ADMIN_GROUP_ID
        sync: false
    healthCheckPath: /health
    autoDeploy: true
