services:
  - type: web
    name: newrest-worker-bot
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: ADMIN_GROUP_ID
        sync: false
      - key: GOOGLE_SHEETS_ID
        sync: false
      - key: GOOGLE_SERVICE_ACCOUNT_PATH
        sync: false
    healthCheckPath: /health
    autoDeploy: true
